### PR TITLE
Reworked import process

### PR DESCRIPTION
**Pull request by helmertz**
This should probably be tested by someone else as well before merging. If something isn't explained, don't hesitate to ask.

- The exercise list on the main course page, and the archive, will be in sync. Rather than fetching from GitHub when the page is visited, exercises will be fetched from a subdirectory containing imported exercises at the same host.
- A new Python script is used for importing, but it essentially has the same functionality as the previous Node script.
- The import script looks for a list of additional files associated with the exercise and automatically adds links in the READMEs, as well as includes them in the downloadable archive. An exercise needs to have a file called `files.json` at its root if there are additional files the students should have access to. The file should contain a JSON list of the relative paths to each file.
- See the modified `README.md` for more information about the import process.

### CODE REVIEW

**Comment by Dr-Horv** [comment]
> A new Python script is used for importing, but it essentially has the same functionality as the previous Node script.

If so, why not keep the proved working node-script? I'll try to find time to take a closer look and run this over the weekend

**Comment by martinlofgren** [comment]
> > A new Python script is used for importing, but it essentially has the same functionality as the previous Node script.

> If so, why not keep the proved working node-script?

I would say that the python import script differs enough from the node script to justify it's existence. This is summarized in the third point:

> The import script looks for a list of additional files associated with the exercise and automatically adds links in the READMEs, as well as includes them in the downloadable archive. An exercise needs to have a file called files.json at its root if there are additional files the students should have access to. The file should contain a JSON list of the relative paths to each file.

This automatizes a few steps that needed to be done by hand before and reduces the administrative work.

**Comment by helmertz** [comment]
>> A new Python script is used for importing, but it essentially has the same functionality as the previous Node script.
>
> If so, why not keep the proved working node-script?

The reason for changing anything was to make files associated with exercises available to students in a more automated way. I started out modifying the existing Node script to include them in the archive, but I wasn't able to create the appropriate zip directory structure with the library used (not saying that it's not possible). Having done similar things in Python before, I wrote the Python script instead. Along with writing it came the other design differences. However, I'm not very attached to any change and wouldn't mind alternative solutions.

**Comment by niklasbroberg** [comment]
I quite like having a python solution, since that means I understand it. :)

Has this been tested as requested? Is it ready for merging?

**Comment by martinlofgren** [comment]
I have tested it while working on the site, and I would say it is ready for merging.

**Pull request merged**
